### ISSUE TITLE
Crash in SplittedDataLoader

### ISSUE THREAD

**Issue by trushkin-ilya** [trushkin-ilya/face-anti-spoofer#20]
```
File "train.py", line 44, in <module>
    dataloader = utils.SplittedDataLoader(dataset, args.train_batch_size, args.val_batch_size, args.num_workers)
  File "/home/agruzdev/git/face-anti-spoofer/utils.py", line 7, in init
    val_q = len(dataset) // sum(split) * split[1]
TypeError: 'int' object is not iterable
```

**Comment by trushkin-ilya** [comment]
```
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    optimizer=optim.Adam(model.parameters(), lr=args.lr))
  File "train.py", line 21, in train
    f'Epoch: {epoch + 1}/{args.epochs}\tBatch: {i + 1}/{len(train_loader)}\tLoss: {loss.item()}')
NameError: name 'train_loader' is not defined
```
